skills_db = [
    "python",
    "java",
    "c++",
    "sql",
    "mysql",
    "postgresql",
    "machine learning",
    "deep learning",
    "nlp",
    "tensorflow",
    "pytorch",
    "scikit-learn",
    "flask",
    "django",
    "fastapi",
    "streamlit",
    "aws",
    "docker",
    "git",
    "github",
    "linux",
    "react",
    "nodejs",
    "mongodb",
    "opencv"
]